x86_64-elf-gcc  -fno-builtin -fno-pic -m32 -nostdinc -Iinclude -O -o out/bootmain.o -c kernel/bootmain.c
x86_64-elf-gcc  -fno-builtin -fno-pic -m32 -nostdinc -Iinclude -o out/bootasm.o -c kernel/bootasm.S
x86_64-elf-ld  -m elf_i386 -nostdlib -N -e start -Ttext 0x7C00 -o out/bootblock.o out/bootasm.o out/bootmain.o
objdump -S out/bootblock.o > out/bootblock.asm
/opt/homebrew/opt/llvm/bin/llvm-objcopy  -S -O binary -j .text out/bootblock.o out/bootblock
tools/sign.pl out/bootblock
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/bio.o kernel/bio.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/console.o kernel/console.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/exec.o kernel/exec.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/file.o kernel/file.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/fs.o kernel/fs.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/ide.o kernel/ide.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/ioapic.o kernel/ioapic.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/kalloc.o kernel/kalloc.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/kbd.o kernel/kbd.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/lapic.o kernel/lapic.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/log.o kernel/log.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/main.o kernel/main.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/mp.o kernel/mp.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/acpi.o kernel/acpi.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/picirq.o kernel/picirq.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/pipe.o kernel/pipe.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/proc.o kernel/proc.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/spinlock.o kernel/spinlock.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/string.o kernel/string.c
x86_64-elf-gcc  -fno-pic -gdwarf-2 -Wa,-divide -Iinclude -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -c -o kobj/swtch64.o kernel/swtch64.S
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/syscall.o kernel/syscall.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/sysfile.o kernel/sysfile.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/sysproc.o kernel/sysproc.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/timer.o kernel/timer.c
x86_64-elf-gcc  -fno-pic -gdwarf-2 -Wa,-divide -Iinclude -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -c -o kobj/trapasm64.o kernel/trapasm64.S
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/trap.o kernel/trap.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/uart.o kernel/uart.c
perl tools/vectors64.pl > kernel/vectors.S
x86_64-elf-gcc  -fno-pic -gdwarf-2 -Wa,-divide -Iinclude -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -c -o kobj/vectors.o kernel/vectors.S
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/vm.o kernel/vm.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/graphics.o kernel/graphics.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/window_manager.o kernel/window_manager.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/mouse.o kernel/mouse.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/msg.o kernel/msg.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/cmos.o kernel/cmos.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/bga.o kernel/bga.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/pci.o kernel/pci.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/gui.o kernel/gui.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/amiga/amiga.o kernel/amiga/amiga.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/libc/stdio.o kernel/libc/stdio.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/libc/stdlib.o kernel/libc/stdlib.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o kobj/vm64.o kernel/vm64.c
x86_64-elf-gcc  -fno-pic -gdwarf-2 -Wa,-divide -Iinclude -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -c -o kobj/entry64.o kernel/entry64.S
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -fno-pic -nostdinc -I. -o out/entryother.o -c kernel/entryother.S
x86_64-elf-ld  -m elf_x86_64 -nostdlib  -N -e start -Ttext 0x7000 -o out/bootblockother.o out/entryother.o
/opt/homebrew/opt/llvm/bin/llvm-objcopy  -S -O binary -j .text out/bootblockother.o out/entryother
objdump -S out/bootblockother.o > out/entryother.asm
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -nostdinc -I. -o out/initcode.o -c kernel/initcode64.S
x86_64-elf-ld  -m elf_x86_64 -nostdlib  -N -e start -Ttext 0 -o out/initcode.out out/initcode.o
/opt/homebrew/opt/llvm/bin/llvm-objcopy  -S -O binary out/initcode.out out/initcode
objdump -S out/initcode.o > out/initcode.asm
x86_64-elf-ld  -m elf_x86_64 -nostdlib  -T kernel/kernel64.ld -o out/kernel.elf kobj/entry64.o kobj/bio.o kobj/console.o kobj/exec.o kobj/file.o kobj/fs.o kobj/ide.o kobj/ioapic.o kobj/kalloc.o kobj/kbd.o kobj/lapic.o kobj/log.o kobj/main.o kobj/mp.o kobj/acpi.o kobj/picirq.o kobj/pipe.o kobj/proc.o kobj/spinlock.o kobj/string.o kobj/swtch64.o kobj/syscall.o kobj/sysfile.o kobj/sysproc.o kobj/timer.o kobj/trapasm64.o kobj/trap.o kobj/uart.o kobj/vectors.o kobj/vm.o kobj/graphics.o kobj/window_manager.o kobj/mouse.o kobj/msg.o kobj/cmos.o kobj/bga.o kobj/pci.o kobj/gui.o kobj/amiga/amiga.o kobj/libc/stdio.o kobj/libc/stdlib.o kobj/vm64.o -b binary out/initcode out/entryother 
objdump -S out/kernel.elf > out/kernel.asm
objdump -t out/kernel.elf | sed '1,/SYMBOL TABLE/d; s/ .* / /; /^$/d' > out/kernel.sym
gcc -Werror -Wall -o out/mkfs tools/mkfs.c
x86_64-elf-gcc  -fno-pic -gdwarf-2 -Wa,-divide -Iinclude -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -c -o uobj/usys.o ulib/usys.S
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o uobj/printf.o ulib/printf.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o uobj/umalloc.o ulib/umalloc.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o uobj/hashtable.o ulib/hashtable.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o uobj/sprintf.o ulib/sprintf.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o uobj/user_window.o ulib/user_window.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o uobj/user_handler.o ulib/user_handler.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o uobj/bitmap.o ulib/bitmap.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o shell_obj/parser.o shell_lib/parser.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o shell_obj/history.o shell_lib/history.c
x86_64-elf-gcc  -fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -fno-omit-frame-pointer -ffreestanding -fno-common -nostdlib -Iinclude -gdwarf-2 -m64 -DX64 -mcmodel=kernel -mtls-direct-seg-refs -mno-red-zone -O0  -fno-stack-protector -c -o shell_obj/input.o shell_lib/input.c
